export const joiErrorMessages = {
  "any.required": "El campo {#label} es requerido",
  "string.base": 'El valor de "{#label}" debe ser una cadena',
  "string.empty": "El campo {#label} no debe estar vacío",
  "number.base": "El valor de {#label} debe ser un número",
  "number.max": "El archivo no debe exceder los 5 MB",
  "object.base": "El valor de {#label} debe ser un objeto",
  "any.only": "Solo se permiten fotos jpeg o png",
  "string.email": "Formato de email no valido",
  "string.pattern.base": "Formato de password no valido",
  "string.min": "El campo {#label} debe tener al menos {#limit} caracteres",
  "string.max": "El campo {#label} no debe exceder los {#limit} caracteres",
  "object.unknown": "No se permiten campos adicionales en este objeto",
  "boolean.base": 'El valor de "{#label}" debe ser un booleano',
};
